#!/bin/bash

configure_aws_profile() {
  read -p "Enter your AWS Access Key ID: " access_key_id
  read -p "Enter your AWS Secret Access Key: " secret_access_key
  read -p "Enter your AWS Session Token: " session_token
  read -p "Enter your AWS Profile name: " profile_name

  aws configure set aws_access_key_id "$access_key_id" --profile "$profile_name"
  aws configure set aws_secret_access_key "$secret_access_key" --profile "$profile_name"
  aws configure set aws_session_token "$session_token" --profile "$profile_name"

  export AWS_PROFILE="$profile_name"

  echo "AWS profile $profile_name is configured."

  aws sts get-caller-identity --profile "$profile_name"

  read -p "Do those credentials look correct? y/n: " correct

  if [ "$correct" == "y" ]; then
    echo "Setting up AWS environment"
    source start-ups/bin/activate
    python login-table-script.py
    python music-table-script.py
    python upload-to-s3.py
  else
    echo "Please re-run the script and enter the correct credentials."
  fi
}

# Check if the OS is running on an M3 silicon chip
cpu_arch=$(uname -m)
if [[ "$cpu_arch" == "arm64" ]]; then
  echo "Detected M3 silicon chip. Configuring AWS profile..."
  configure_aws_profile
else
  echo "Non-M3 chip detected. Executing only the Python steps..."
  source start-ups/bin/activate
  python login-table-script.py
  python music-table-script.py
  python upload-to-s3.py
fi
